const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('electronAPI', {
    prosesLogin: (username, password) => ipcRenderer.invoke('proses-login', username, password),
    ambilPengaturan: () => ipcRenderer.invoke('ambil-pengaturan'),
    uploadFileLogo: (mime, base64, pos) => ipcRenderer.invoke('upload-file-logo', mime, base64, pos),
    simpanPengaturanKop: (data) => ipcRenderer.invoke('simpan-pengaturan-kop', data),
    perbaruiProfilUser: (userLama, dataBaru) => ipcRenderer.invoke('perbarui-profil-user', userLama, dataBaru),
    ambilKodeKlasifikasiSurat: () => ipcRenderer.invoke('ambil-kode-klasifikasi-surat'),
    hapusKodeKlasifikasi: (kode) => ipcRenderer.invoke('hapus-kode-klasifikasi', kode),
    tambahKodeKlasifikasiSurat: (data) => ipcRenderer.invoke('tambah-kode-klasifikasi-surat', data),
    simpanPengaturanTtd: (data) => ipcRenderer.invoke('simpan-pengaturan-ttd', data),
    cekNomorDuplikat: (urutan, tahun) => ipcRenderer.invoke('cek-nomor-duplikat', urutan, tahun),
    simpanPaketSuratLengkap: (data) => ipcRenderer.invoke('simpan-paket-surat-lengkap', data),
    simpanTemplateDinamis: (payload) => ipcRenderer.invoke('simpan-template-dinamis', payload),
    hapusSemuaTemplate: () => ipcRenderer.invoke('hapus-semua-template'),
    imporTemplatesBatch: (data) => ipcRenderer.invoke('impor-templates-batch', data),
    cariSiswa: (q) => ipcRenderer.invoke('cari-siswa', q),
    simpanSiswaBaru: (data) => ipcRenderer.invoke('simpan-siswa-baru', data),
    hapusSiswa: (nisn) => ipcRenderer.invoke('hapus-siswa', nisn),
    imporSiswaBatch: (data) => ipcRenderer.invoke('impor-siswa-batch', data),
    ambilSemuaTemplate: () => ipcRenderer.invoke('ambil-semua-template'),
    ambilSemuaSiswa: () => ipcRenderer.invoke('ambil-semua-siswa'),
    dapatkanRiwayatArsip: () => ipcRenderer.invoke('dapatkan-riwayat-arsip'),
    ambilDataArsipUntukEkspor: (tahun) => ipcRenderer.invoke('ambil-data-arsip-untuk-ekspor', tahun),
    hapusDataArsip: (id, nomor) => ipcRenderer.invoke('hapus-data-arsip', id, nomor),
    cariGuru: (q) => ipcRenderer.invoke('cari-guru', q),
    ambilSemuaGuru: () => ipcRenderer.invoke('ambil-semua-guru'),
    hapusGuru: (nip) => ipcRenderer.invoke('hapus-guru', nip),
    simpanGuruBaru: (data) => ipcRenderer.invoke('simpan-guru-baru', data),
    imporGuruBatch: (data) => ipcRenderer.invoke('impor-guru-batch', data),
    hapusTemplateSatu: (nama) => ipcRenderer.invoke('hapus-template-satu', nama),
    simpanDatabaseUser: (data) => ipcRenderer.invoke('simpan-database-user', data),
    ambilSemuaUser: () => ipcRenderer.invoke('ambil-semua-user'),
    hapusUserDatabase: (username) => ipcRenderer.invoke('hapus-user-database', username),
    simpanSuratMasukOCR: (meta, base64, mime) => ipcRenderer.invoke('simpan-surat-masuk-ocr', meta, base64, mime),
    dapatkanRiwayatSuratMasuk: () => ipcRenderer.invoke('dapatkan-riwayat-surat-masuk'),
    ambilDataSuratMasukUntukEkspor: (tahun) => ipcRenderer.invoke('ambil-data-surat-masuk-untuk-ekspor', tahun),
    generateNomorSuratOtomatis: (kode) => ipcRenderer.invoke('generate-nomor-surat-otomatis', kode),
    cekFullNomorDuplikat: (nomor) => ipcRenderer.invoke('cek-full-nomor-duplikat', nomor),
    verifikasiSuratByUid: (uid) => ipcRenderer.invoke('verifikasi-surat-by-uid', uid),
    dapatkanUrlSkrip: () => ipcRenderer.invoke('dapatkan-url-skrip'),
    dapatkanGasUrl: () => ipcRenderer.invoke('dapatkan-gas-url'),
    updateGasUrl: (url) => ipcRenderer.invoke('update-gas-url', url),
    onDatabaseSynced: (callback) => ipcRenderer.on('database-synced', (event, ...args) => callback(...args)),
    onSyncStatus: (callback) => ipcRenderer.on('sync-status', (event, status, message) => callback(status, message)),
    ambilPrinters: () => ipcRenderer.invoke('ambil-printers'),
    generatePdfPreview: () => ipcRenderer.invoke('generate-pdf-preview'),
    simpanSebagaiPdf: (defaultName) => ipcRenderer.invoke('simpan-sebagai-pdf', defaultName),
    printDokumenKustom: (printerName, copies) => ipcRenderer.invoke('print-dokumen-kustom', printerName, copies),
    onUpdateAvailable: (callback) => ipcRenderer.on('update_available', () => callback()),
    onUpdateProgress: (callback) => ipcRenderer.on('update_progress', (event, progressObj) => callback(progressObj)),
    onUpdateDownloaded: (callback) => ipcRenderer.on('update_downloaded', () => callback()),
    sinkronisasiOtomatis: () => ipcRenderer.invoke('sinkronisasi-otomatis'),
    restartApp: () => ipcRenderer.invoke('restart_app'),
});
